import alaves from './image/alaves.png';
import atletico from './image/atletico.png';
import barca from './image/barca.png';
import bilbao from './image/bilbao.png';
import cadiz from './image/cadiz.png';
import celta from './image/celta.png';
import eibar from './image/eibar.png';
import elche from './image/elche.png';
import getafe from './image/getafe.png';
import granada from './image/granada.png';
import huesca from './image/huesca.png';
import levante from './image/levante.png';
import osasuna from './image/osasuna.png';
import real_betis from './image/real_betis.png';
import real_madrid from './image/real_madrid.png';
import sevilla from './image/sevilla.png';
import sociedad from './image/sociedad.png';
import valencia from './image/valencia.png';
import valladolid from './image/valladolid.png';
import villareal from './image/villareal.png';

const clubs = [
  {
    id: 1,
    name: 'Athletic Bilbao',
    full_name: 'Athletic Bilbao',
    nickname: 'Los Leones (The Lions)',
    stadium: 'San Mamés',
    coach: 'Marcelino',
    logo: bilbao,
    city: 'Bilbao',
    foundation: '1898',
    website: 'http://www.athletic-club.eus/en/home.html',
  },
  {
    id: 2,
    name: 'Atlético Madrid',
    full_name: 'Club Atlético de Madrid',
    nickname: '',
    stadium: 'Wanda Metropolitano',
    coach: 'Diego Simeone',
    logo: atletico,
    city: 'Madrid',
    foundation: '1903',
    website: 'http://en.atleticodemadrid.com/',
  },
  {
    id: 3,
    name: 'CA Osasuna',
    full_name: 'Club Atlético Osasuna',
    nickname: 'Gorritxoak, Los Rojillos',
    stadium: 'El Sadar',
    coach: 'Jagoba Arrasate',
    logo: osasuna,
    city: 'Pamplona',
    foundation: '1920',
    website: 'http://www.osasuna.es/',
  },
  {
    id: 4,
    name: 'Cádiz CF',
    full_name: 'Cádiz Club de Fútbol',
    nickname: 'Los Piratas, El Submarino Amarillo',
    stadium: 'Ramón de Carranza',
    coach: 'Álvaro Cervera',
    logo: cadiz,
    city: 'Cádiz',
    foundation: '1910',
    website: 'http://www.cadizcf.com/',
  },
  {
    id: 5,
    name: 'Deportivo Alavés',
    full_name: 'Deportivo Alavés',
    nickname: 'Babazorros, El Glorioso (The glorious one)',
    stadium: 'Mendizorrotza',
    coach: 'Abelardo Fernández',
    logo: alaves,
    city: 'Vitoria-Gasteiz',
    foundation: '1921',
    website: 'http://www.alaves.com/',
  },
  {
    id: 6,
    name: 'Elche CF',
    full_name: 'Elche Club de Fútbol',
    nickname: 'Los Franjiverdes / Els frangiverds (The Green-striped ones)',
    stadium: 'Estadio Manuel Martínez Valero',
    coach: 'Fran Escribá',
    logo: elche,
    city: '  Elche',
    foundation: '1923',
    website: 'http://www.elchecf.es/',
  },
  {
    id: 7,
    name: 'FC Barcelona',
    full_name: 'Futbol Club Barcelona',
    nickname: 'Barça or Blaugrana, Culers',
    stadium: 'Camp Nou',
    coach: 'Ronald Koeman',
    logo: barca,
    city: 'Barcelona',
    foundation: '1899',
    website: 'http://www.fcbarcelona.com/',
  },
  {
    id: 8,
    name: 'Getafe CF',
    full_name: 'Getafe Club de Fútbol',
    nickname: '',
    stadium: 'Coliseum Alfonso Pérez',
    coach: 'José Bordalás',
    logo: getafe,
    city: 'Getafe',
    foundation: '1983',
    website: 'https://www.getafecf.com/',
  },
  {
    id: 9,
    name: 'Granada CF',
    full_name: 'Granada Club de Fútbol',
    nickname: 'Nazaríes (Nasrids)',
    stadium: 'Nuevo Los Cármenes Stadium',
    coach: 'Diego Martínez',
    logo: granada,
    city: 'Granada',
    foundation: '1931',
    website: 'http://www.granadacf.es/',
  },
  {
    id: 10,
    name: 'Levante UD',
    full_name: 'Levante Unión Deportiva',
    nickname: 'Granotas (The Frogs)',
    stadium: 'Ciutat de València',
    coach: 'Paco López',
    logo: levante,
    city: ' Valencia',
    foundation: '1909',
    website: 'http://www.levanteud.com/',
  },
  {
    id: 11,
    name: 'RC Celta',
    full_name: 'Real Club Celta de Vigo',
    nickname: 'Los/Os Celestes (The Sky Blues)',
    stadium: 'Balaídos',
    coach: 'Eduardo Coudet',
    logo: celta,
    city: ' Vigo',
    foundation: '1923',
    website: 'http://www.rccelta.es/',
  },
  {
    id: 12,
    name: 'Real Betis',
    full_name: 'Real Betis Balompié',
    nickname: 'Los Verdiblancos (The Green-and-Whites), Heliopolitanos (Heliopolitans)',
    stadium: 'Estadio Benito Villamarín',
    coach: 'Manuel Pellegrini',
    logo: real_betis,
    city: 'Seville',
    foundation: '1907',
    website: 'http://www.realbetisbalompie.es/',
  },
  {
    id: 13,
    name: 'Real Madrid',
    full_name: 'Real Madrid Club de Fútbol',
    nickname: 'Los Blancos (The Whites), La Casa Blanca (The White House)',
    stadium: 'Estadio Santiago Bernabéu',
    coach: 'Zinedine Zidane',
    logo: real_madrid,
    city: 'Madrid',
    foundation: '1902',
    website: 'http://www.realmadrid.com/',
  },
  {
    id: 14,
    name: 'Real Sociedad',
    full_name: 'Real Sociedad de Fútbol',
    nickname: 'Los Txuri-Urdin (The White and Blues)',
    stadium: 'Anoeta Stadium',
    coach: 'Imanol Alguacil',
    logo: sociedad,
    city: 'San Sebastián',
    foundation: '1909',
    website: 'https://www.realsociedad.eus/en',
  },
  {
    id: 15,
    name: 'Real Valladolid CF',
    full_name: 'Real Valladolid Club de Fútbol',
    nickname: 'Pucela / Pucelanos (Pucelle)',
    stadium: 'José Zorrilla',
    coach: 'Sergio González',
    logo: valladolid,
    city: 'Valladolid',
    foundation: '1928',
    website: 'http://www.realvalladolid.es/',
  },
  {
    id: 16,
    name: 'SD Eibar',
    full_name: 'Sociedad Deportiva Eibar',
    nickname: 'Armagiñak / Los Armeros (The Gunsmiths)',
    stadium: 'Ipurua Municipal Stadium',
    coach: 'José Luis Mendilibar',
    logo: eibar,
    city: ' Eibar',
    foundation: '1940',
    website: 'http://www.sdeibar.com/',
  },
  {
    id: 17,
    name: 'SD Huesca',
    full_name: 'Sociedad Deportiva Huesca',
    nickname: 'Oscenses, Azulgranas',
    stadium: 'El Alcoraz',
    coach: 'Pacheta',
    logo: huesca,
    city: 'Huesca',
    foundation: '1960',
    website: 'http://www.sdhuesca.es/',
  },
  {
    id: 18,
    name: 'Sevilla FC',
    full_name: 'Sevilla Fútbol Club',
    nickname: 'Los Nervionenses/Los Palanganas',
    stadium: 'Estadio Ramón Sánchez Pizjuán',
    coach: 'Julen Lopetegui',
    logo: sevilla,
    city: ' Seville',
    foundation: '1905',
    website: 'https://www.sevillafc.es/',
  },
  {
    id: 19,
    name: 'Valencia CF',
    full_name: 'Valencia Club de Fútbol',
    nickname: 'Los murciélagos (The Bats)',
    stadium: 'Mestalla',
    coach: 'Javi Gracia',
    logo: valencia,
    city: 'Valencia',
    foundation: '1919',
    website: 'http://www.valenciacf.com/',
  },
  {
    id: 20,
    name: 'Villarreal CF',
    full_name: 'Villarreal Club de Fútbol',
    nickname: 'El Submarino Amarillo (The Yellow Submarine)',
    stadium: 'Estadio de la Cerámica',
    coach: 'Unai Emery',
    logo: villareal,
    city: 'Villarreal',
    foundation: '1923',
    website: 'http://www.villarrealcf.es/',
  },
];
